[config]
default_to_workspace = false
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]


[tasks.calc-project-loc]
command = "./scripts/calc_project_loc.sh"
args = [".", "rs"]


[tasks.clean]
command = "cargo"
args = ["clean"]
